version: 2.1

jobs:
  build:
    docker:
    - image: ruby:2.4.0-jessie
    steps:
    - run: echo 'export API_TOKEN="204b008b81e09a98cace13a71ce213eb6026f0d7"' >> $BASH_ENV
    - run: |
        echo first step
        echo $CIRCLE_PREVIOUS_BUILD_NUM
        echo $CIRCLE_BUILD_NUM
        echo $CIRCLE_USERNAME
        echo $CIRCLE_PROJECT_USERNAME
        echo $CIRCLE_PROJECT_REPONAME
        echo $CIRCLE_NODE_TOTAL
        exit 1
    - run:
        name: when on_fail
        command: |
          echo run on_fail_1
        when: on_fail
    - run:
        name: when on_fail 2
        command: |
          curl -X POST https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/retry -H "Circle-Token: ${API_TOKEN}"
        when: on_fail
    - run:
        name: when always
        command:
          echo always run
        when: always
    - run:
        name: when on_success
        command:
          echo on_success
        when: on_success
    - run:
        name: last step
        command:
          echo LAST RUN
