version: 2.1

jobs:
  build:
    docker:
    - image: alpine
    steps:
    - run: |
        echo first step
        echo $CIRCLE_PREVIOUS_BUILD_NUM
        echo $CIRCLE_BUILD_NUM
        echo $CIRCLE_USERNAME
        echo $CIRCLE_PROJECT_USERNAME
        echo $CIRCLE_PROJECT_REPONAME
        echo $CIRCLE_NODE_TOTAL
        if [$CIRCLE_BUILD_NUM <= 9]; then
          exit 1
        fi
    - run:
        name: when on_fail
        command: |
          echo run on_fail_1
        when: on_fail
    - run:
        name: when on_fail 2
        command:
          echo run on_fail_2
        when: on_fail
    - run:
        name: when always
        command:
          echo always run
        when: always
    - run:
        name: when on_success
        command:
          echo on_success
        when: on_success
    - run:
        name: last step
        command:
          echo LAST RUN
